services:
    novaas:
        build: .
        image: "registry.gitlab.com/novaas/catalog/nova-school-of-science-and-technology/novaas-prosys-opc-ua-simulation-server:latest"
        environment:
            - "PORT_FORWARDING=${PORT_FORWARDING}" 
            - "HOST=${HOST}"
            - "BROKER_SERVICE_HOST=${BROKER_SERVICE_HOST}"
            - "BROKER_SERVICE_PORT=${BROKER_SERVICE_PORT}"
            - "REPO_LOCATION=${REPO_LOCATION}"
            - "PROSYS_OPCUA_SERVICE=${PROSYS_OPCUA_SERVICE}"
        ports:
            - "${PORT_FORWARDING}:1880"